# HTTP Server
server:
  port: 17853  # HTTP (Tomcat) port

#spring:
#  data:
#    mongodb:
#      host: ts-notification-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017


#  main:
#    banner-mode: off

#  velocity:
#    resource-loader-path: classpath:/templates/
#    check-template-location: true